import { Request, Response } from 'express';
import { prisma } from '../config/db';
import { watermarkImage } from '../utils/watermark';

// Create new Lease Agreement (generated by landlord)
export const createAgreement = async (req: Request, res: Response) => {
  try {
    const {
      tenantName,
      tenantEmail,
      landlordName,
      landlordEmail,
      monthlyRent,
      securityDeposit,
      termLength,
      startDate,
      endDate,
      listingName,
      contractText,
      landlordSig
    } = req.body;

    if (!tenantName || !tenantEmail || !landlordName || !landlordEmail || !listingName || !contractText) {
      return res.status(400).json({ error: 'Missing required lease parameters.' });
    }

    const newAgreement = await prisma.leaseAgreement.create({
      data: {
        tenantName,
        tenantEmail,
        landlordName,
        landlordEmail,
        monthlyRent: Number(monthlyRent) || 0,
        securityDeposit: Number(securityDeposit) || 0,
        termLength: termLength || '12 Months',
        startDate,
        endDate,
        listingName,
        contractText,
        landlordSig,
        status: 'Pending Signatures'
      }
    });

    res.status(201).json(newAgreement);
  } catch (error) {
    console.error('Error creating lease agreement:', error);
    res.status(500).json({ error: 'Internal server error' });
  }
};

// Get list of Lease Agreements (supports tenantEmail query parameter)
export const getAgreements = async (req: Request, res: Response) => {
  try {
    const { tenantEmail, landlordEmail } = req.query;

    const filter: any = {};
    if (tenantEmail) {
      filter.tenantEmail = String(tenantEmail);
    }
    if (landlordEmail) {
      filter.landlordEmail = String(landlordEmail);
    }

    const agreements = await prisma.leaseAgreement.findMany({
      where: filter,
      orderBy: { createdAt: 'desc' }
    });

    res.status(200).json(agreements);
  } catch (error) {
    console.error('Error fetching lease agreements:', error);
    res.status(500).json({ error: 'Internal server error' });
  }
};

// Get single Lease Agreement details by ID
export const getAgreementById = async (req: Request, res: Response) => {
  try {
    const { id } = req.params;

    const agreement = await prisma.leaseAgreement.findUnique({
      where: { id }
    });

    if (!agreement) {
      return res.status(404).json({ error: 'Lease agreement not found.' });
    }

    res.status(200).json(agreement);
  } catch (error) {
    console.error('Error fetching lease agreement:', error);
    res.status(500).json({ error: 'Internal server error' });
  }
};

// Sign Lease Agreement (by tenant)
export const signAgreement = async (req: Request, res: Response) => {
  try {
    const { id } = req.params;
    const { tenantSig, nicFront, nicBack } = req.body;

    if (!tenantSig) {
      return res.status(400).json({ error: 'Tenant signature is required to sign agreement.' });
    }

    if (!nicFront || !nicBack) {
      return res.status(400).json({ error: 'Both NIC Front and Back images are required to complete lease verification.' });
    }

    const agreement = await prisma.leaseAgreement.findUnique({
      where: { id }
    });

    if (!agreement) {
      return res.status(404).json({ error: 'Lease agreement not found.' });
    }

    // Apply diagonal watermark to secure uploaded identity cards
    let watermarkedFront = nicFront;
    let watermarkedBack = nicBack;

    if (nicFront) {
      watermarkedFront = await watermarkImage(nicFront);
    }
    if (nicBack) {
      watermarkedBack = await watermarkImage(nicBack);
    }

    // Update the Tenant User record with watermarked identity cards
    if (agreement.tenantEmail) {
      try {
        await prisma.user.update({
          where: { email: agreement.tenantEmail },
          data: {
            nicFront: watermarkedFront,
            nicBack: watermarkedBack
          }
        });
      } catch (userErr) {
        console.warn(`Could not update tenant user NIC copy (user may not have registered yet):`, userErr);
      }
    }

    const updated = await prisma.leaseAgreement.update({
      where: { id },
      data: {
        tenantSig,
        status: 'Active' // Both landlord and tenant have signed now!
      }
    });

    res.status(200).json(updated);
  } catch (error) {
    console.error('Error signing lease agreement:', error);
    res.status(500).json({ error: 'Internal server error' });
  }
};

// Save / unsave agreement in user's wallet
export const saveToWallet = async (req: Request, res: Response) => {
  try {
    const { id } = req.params;
    const { role, saved } = req.body; // role: 'landlord' | 'tenant', saved: boolean

    if (role !== 'landlord' && role !== 'tenant') {
      return res.status(400).json({ error: "Invalid role specified. Must be 'landlord' or 'tenant'." });
    }

    const updateData: any = {};
    if (role === 'landlord') {
      updateData.savedInLandlordWallet = saved !== undefined ? saved : true;
    } else {
      updateData.savedInTenantWallet = saved !== undefined ? saved : true;
    }

    const updated = await prisma.leaseAgreement.update({
      where: { id },
      data: updateData
    });

    res.status(200).json(updated);
  } catch (error) {
    console.error('Error saving agreement to wallet:', error);
    res.status(500).json({ error: 'Internal server error' });
  }
};

